### ISSUE TITLE
Upgrade digest and md4 versions

### ISSUE THREAD

**Issue by ghost** [runfalk/ed2k-rs#1]
I've tried upgrading the digest and md4 versions but it gave me many errors, and I don't know how to fix them. I've been looking at the [other hash functions](https://github.com/RustCrypto/hashes) using digest but they are all different, they all use different digest functions and I don't know what I have to change.

Could you try to upgrade the digest and md4 versions? If you don't want to do it, could you tell me how did you manage to learn how to do it?

**Comment by runfalk** [comment]
I updated it. I learnt how to do the hasher by looking at the MD4 implementation and reading the `digest` crate docs.
